#!/bin/dash

# check .legit directory
if ! test -d .legit
then
	echo "legit-log: error: no .legit directory containing legit repository exists"
	exit
fi

l=`ls .legit/repo/ | wc -l`

if [ $l = 0 ]
then
	echo "legit-log: error: your repository does not have any commits yet"
	exit
fi

sort -nr  .legit/commit-log